### ISSUE TITLE
Script is not working with latest master (38ca558961652b29d80b0b08c9cfa078cc0e3891)

### ISSUE THREAD

**Issue by destogl** [lucmos/UltrawideWindows#27] opened 2021-08-17 06:31 UTC
With latest master, I have an issue running the script. There are no obvious issues (at least for me), but the shortcuts are simply not accepted/responding.

I get this output when run the `update.sh`:

```
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3801, resource id: 178257987, major code: 3 (GetWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 3802, resource id: 178257987, major code: 14 (GetGeometry), minor code: 0
OpenGL vendor string:                   Intel
OpenGL renderer string:                 Mesa Intel(R) HD Graphics 620 (KBL GT2)
OpenGL version string:                  4.6 (Compatibility Profile) Mesa 21.0.3
OpenGL shading language version string: 4.60
Driver:                                 Intel
GPU class:                              Unknown
OpenGL version:                         4.6
GLSL version:                           4.60
Mesa version:                           21.0.3
X server version:                       1.20.11
Linux kernel version:                   5.4
Requires strict binding:                yes
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4090, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4091, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4092, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4093, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4094, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4095, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4096, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4097, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4100, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4101, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4102, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4103, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4104, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4105, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4106, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 4107, resource id: 0, major code: 14 (GetGeometry), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 8 (BadMatch), sequence: 9801, resource id: 54525959, major code: 42 (SetInputFocus), minor code: 0
```

For testing I tried to checkout merge of (my) PR #22 (commit: 670dd9a6e728692e42fbb27a5043878c20d5fcb8) and then the scortcuts are working again. In this case the output of the `update.sh` script is:

```
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3687, resource id: 37748799, major code: 3 (GetWindowAttributes), minor code: 0
OpenGL vendor string:                   Intel
OpenGL renderer string:                 Mesa Intel(R) HD Graphics 620 (KBL GT2)
OpenGL version string:                  4.6 (Compatibility Profile) Mesa 21.0.3
OpenGL shading language version string: 4.60
Driver:                                 Intel
GPU class:                              Unknown
OpenGL version:                         4.6
GLSL version:                           4.60
Mesa version:                           21.0.3
X server version:                       1.20.11
Linux kernel version:                   5.4
Requires strict binding:                yes
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
```

Does anybody has idea what is happening here? I am not sure what is changed between 670dd9a6e728692e42fbb27a5043878c20d5fcb8 and 38ca558961652b29d80b0b08c9cfa078cc0e3891.

**Comment by lucmos** [comment] 2021-08-17 07:00
Hello, thanks for the bug report!

It would be very useful if you could identify the commit that introduced the problem for you.
You can use `git bisect` on master to identify it

**Comment by Stijn-vdD** [comment] 2021-08-28 16:57
Do you have an update on the problems you're having? If it's caused by something in my contribution I might be able to find a solution somehow.

**Comment by destogl** [comment] 2021-09-16 09:26
@Stijn-vdD sorry didn't have time to figure this out. But, maybe, (just maybe) I manage to replicate this on my new laptop using a different setup. This is the output there:

``
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2707, resource id: 130023450, major code: 3 (GetWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 2708, resource id: 130023450, major code: 14 (GetGeometry), minor code: 0
OpenGL vendor string:                   NVIDIA Corporation
OpenGL renderer string:                 GeForce RTX 3080 Laptop GPU/PCIe/SSE2
OpenGL version string:                  4.6.0 NVIDIA 460.91.03
OpenGL shading language version string: 4.60 NVIDIA
Driver:                                 NVIDIA
Driver version:                         460.91.3
GPU class:                              Unknown
OpenGL version:                         4.6
GLSL version:                           4.60
X server version:                       1.20.11
Linux kernel version:                   5.11
Requires strict binding:                no
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
kf5.ki18n: "Interpolation {$[gen %1]} in { &Podešavanje $[gen ...} failed: Unregistered call to 'gen'."
kf5.ki18n: "Interpolation {$[aku %1]} in { &Priručnik za $[aku...} failed: Unregistered call to 'aku'."
```

I will try to pin-poin the comment in the next few days.

**Comment by Stijn-vdD** [comment] 2021-11-24 20:00
@destogl I think I might have found a solution to the issue. If you are still interested in the script take a look at issue #28.

**Comment by lucmos** [comment] 2021-11-25 13:53
I rolled back the master, I think we can close this.

For updates see #28

**Closed by lucmos** 2021-11-25 13:53 UTC
